# Generated by Django 3.2.6 on 2021-08-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210811_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_instagram',
            new_name='social_linkedin',
        ),
    ]
