# Generated by Django 3.2.6 on 2021-08-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_social_instagram_profile_social_linkedin'),
        ('projects', '0005_auto_20210827_2043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewiew',
            new_name='Review',
        ),
    ]
